name: Construir e Publicar BarbeCode API no Docker Hub

on:
    push:   
        branches: ["master"]

jobs: 
    build_e_push:
        runs-on: ubuntu-latest

    steps:
       - name: Passo 1 - Fazer o Checkout do Código
         uses: actions/chekout@v4

       - name: Passo 2 - Fazer o Login no Docker Hub
         uses: docker/login-action@v3
         with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Passo 3 - Contruir e Enviar a Imagem Docker (Build and Push)
         uses: docker/build-push-action@v5
         with:
            context: .
            file: src/BarbeCode.API/Dockerfile
            push: true

            tags: matheussanttana1/barbercode-api
