// <auto-generated />
using System;
using BarberCode.Infra.Banco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberCode.Infra.Migrations
{
    [DbContext(typeof(BarberCodeContext))]
    [Migration("20260320143235_Novo")]
    partial class Novo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarberCode.Domain.Entities.Agendamentos.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarbeariaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarbeiroId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId");

                    b.HasIndex("BarbeiroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("barbearias");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.ClienteInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarbeariaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarbeariaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarbeariaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("HorarioAlmoco")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId");

                    b.ToTable("barbeiros");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Agendamentos.Agendamento", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", "Barbearia")
                        .WithMany()
                        .HasForeignKey("BarbeariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberCode.Domain.Entities.Barbeiros.Barbeiro", "Barbeiro")
                        .WithMany("Agendamentos")
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberCode.Domain.Entities.Barbearias.ClienteInfo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbearia");

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.OwnsOne("BarberCode.Domain.Entities.Barbearias.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("BarbeariaId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Lougradouro")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("BarbeariaId");

                            b1.ToTable("barbearias");

                            b1.WithOwner()
                                .HasForeignKey("BarbeariaId");
                        });

                    b.OwnsMany("BarberCode.Domain.Entities.Barbearias.HorarioFuncionamento", "Funcionamento", b1 =>
                        {
                            b1.Property<Guid>("BarbeariaId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time(6)");

                            b1.Property<TimeOnly>("Incio")
                                .HasColumnType("time(6)");

                            b1.Property<int>("dia")
                                .HasColumnType("int");

                            b1.HasKey("BarbeariaId", "Id");

                            b1.ToTable("HorarioFuncionamento");

                            b1.WithOwner()
                                .HasForeignKey("BarbeariaId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Funcionamento");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.ClienteInfo", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", null)
                        .WithMany("Clientes")
                        .HasForeignKey("BarbeariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Servico", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", "Barbearia")
                        .WithMany("Servicos")
                        .HasForeignKey("BarbeariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbearia");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", "BarbeariaQueTrabalha")
                        .WithMany("Barbeiros")
                        .HasForeignKey("BarbeariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarbeariaQueTrabalha");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.Navigation("Barbeiros");

                    b.Navigation("Clientes");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
