// <auto-generated />
using System;
using BarberCode.Infra.Banco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberCode.Infra.Migrations
{
    [DbContext(typeof(BarberCodeContext))]
    [Migration("20260310212528_InicioTeste")]
    partial class InicioTeste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BarbeiroServico", b =>
                {
                    b.Property<Guid>("BarbeirosId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicosPrestadosId")
                        .HasColumnType("char(36)");

                    b.HasKey("BarbeirosId", "ServicosPrestadosId");

                    b.HasIndex("ServicosPrestadosId");

                    b.ToTable("BarbeiroServico");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Agendamentos.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BarbeiroId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.ToTable("agendamentos");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("barbearias");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BarbeariaId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId1");

                    b.ToTable("barbeiros");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("BarbeariaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BarbeariaId");

                    b.ToTable("servicos");
                });

            modelBuilder.Entity("BarbeiroServico", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbeiros.Barbeiro", null)
                        .WithMany()
                        .HasForeignKey("BarbeirosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberCode.Domain.Entities.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosPrestadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Agendamentos.Agendamento", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbeiros.Barbeiro", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("BarbeiroId");

                    b.OwnsOne("BarberCode.Domain.Entities.Agendamentos.ClienteInfo", "Cliente", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<int>("Phone")
                                .HasColumnType("int");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId");
                        });

                    b.Navigation("Cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.OwnsOne("BarberCode.Domain.Entities.Barbearias.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("BarbeariaId")
                                .HasColumnType("char(36)");

                            b1.HasKey("BarbeariaId");

                            b1.ToTable("barbearias");

                            b1.WithOwner()
                                .HasForeignKey("BarbeariaId");
                        });

                    b.OwnsMany("BarberCode.Domain.Entities.Barbearias.HorarioFuncionamento", "Funcionamento", b1 =>
                        {
                            b1.Property<Guid>("BarbeariaId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<TimeOnly>("Fim")
                                .HasColumnType("time(6)");

                            b1.Property<TimeOnly>("Incio")
                                .HasColumnType("time(6)");

                            b1.Property<int>("dia")
                                .HasColumnType("int");

                            b1.HasKey("BarbeariaId", "Id");

                            b1.ToTable("HorarioFuncionamento");

                            b1.WithOwner()
                                .HasForeignKey("BarbeariaId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Funcionamento");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", null)
                        .WithMany("Barbeiros")
                        .HasForeignKey("BarbeariaId1");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Servico", b =>
                {
                    b.HasOne("BarberCode.Domain.Entities.Barbearias.Barbearia", null)
                        .WithMany("Servicos")
                        .HasForeignKey("BarbeariaId");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbearias.Barbearia", b =>
                {
                    b.Navigation("Barbeiros");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("BarberCode.Domain.Entities.Barbeiros.Barbeiro", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
