# Nome da automação que vai aparecer lá na aba "Actions" do GitHub
name: Construir e Publicar BarberCode API no Docker Hub

# 1. O GATILHO (Quando essa automação deve rodar?)
# Aqui estamos dizendo: "Robô, só trabalhe quando código novo chegar na branch main"
on:
  push:
    branches: [ "master" ]

# 2. AS MISSÕES (Jobs)
jobs:
  build_e_push:
    # Escolhemos um computador com Linux atualizado para rodar o processo
    runs-on: ubuntu-latest

    # 3. O PASSO A PASSO
    steps:
      - name: Passo 1 - Fazer o Checkout do Código
        # Essa ferramenta do Marketplace baixa os arquivos do seu repositório para o computador temporário
        uses: actions/checkout@v4

      - name: Passo 2 - Fazer Login no Docker Hub
        # Essa ferramenta do Docker faz o login de forma segura pegando as senhas do seu Cofre
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Passo 3 - Construir e Enviar a Imagem Docker (Build and Push)
        # Essa é a ferramenta principal. Ela substitui os comandos manuais que você fazia no terminal.
        uses: docker/build-push-action@v5
        with:
          # Contexto '.' garante que ele copia a pasta 'src' inteira corretamente
          context: . 
          # Aponta exatamente onde o Dockerfile está escondido
          file: src/BarberCode.API/Dockerfile 
          # O comando mágico que diz: "Sim, após construir, envie para o Docker Hub"
          push: true 
          # O nome e a versão da sua imagem. Usamos 'latest' para atualizar a principal.
          tags: matheussanttana1/barbercode-api:latest

  deploy:
    # A MÁGICA DA DEPENDÊNCIA: O 'needs' diz ao robô que ele é estritamente 
    # proibido de rodar este job se o job 'build' falhar. Isso impede que a 
    # AWS seja atualizada se a imagem não foi gerada corretamente.
    needs: build_e_push
    
    # O GitHub liga um computador Linux novinho em folha só para essa tarefa
    runs-on: ubuntu-latest
    
    steps:
      # Ferramenta do Marketplace que sabe como acessar servidores remotos via SSH
      - uses: appleboy/ssh-action@v1.0.3
        with:
          # Injeção das variáveis de segurança que guardamos no Secrets do GitHub
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          
          # Aqui é o terminal fantasma. Tudo que está abaixo do pipe (|) será 
          # digitado invisivelmente dentro da sua máquina na AWS.
          script: |
            # 1. Navega para a pasta exata onde o seu projeto vive no servidor
            cd /home/ubuntu/barbercode
            
            # 2. Força a AWS a ir no Docker Hub e baixar a versão nova (latest)
            sudo docker compose pull
            
            # 3. Derruba a API antiga de forma mais suave
            sudo docker compose down
            
            # 4. Faz o robô esperar 10 segundos. 
            # Esse é o tempo exato que a Aiven precisa para entender que a API caiu e limpar a memória.
            sleep 10 
            
            # 5. Sobe a API nova, agora com o banco de dados aliviado e pronto pra recebê-la
            sudo docker compose up -d
         
  
    